spring.application.name=frontend
server.port=8080

# Gateway service - используется Consul Discovery + LoadBalancer
gateway.service.name=gateway

# Spring Cloud Consul (Service Discovery)
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.service-name=${spring.application.name}

# Spring Cloud LoadBalancer
spring.cloud.loadbalancer.enabled=true

# Logging
logging.level.ru.yandex.practicum.mybankfront=INFO
logging.level.org.springframework.cloud=INFO
