apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  kibana.yml: |
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    xpack.security.enabled: false
    xpack.fleet.enabled: false
    xpack.encryptedSavedObjects.encryptionKey: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    xpack.reporting.encryptionKey: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
