apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.beatsPort }}
      targetPort: 5044
      protocol: TCP
      name: beats
    - port: {{ .Values.service.tcpPort }}
      targetPort: 5000
      protocol: TCP
      name: tcp
    - port: 9600
      targetPort: 9600
      protocol: TCP
      name: api
  selector:
    app: {{ .Chart.Name }}
