apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns
      protocol: TCP
      name: dns
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-dns
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns
      protocol: UDP
      name: dns-udp
  selector:
    app: {{ .Chart.Name }}
