# Payment Service Configuration
spring.application.name=accounts-service

# Server configuration
server.port=8080

# SpringDoc OpenAPI Configuration
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.default-produces-media-type=application/json

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/bank
spring.r2dbc.username=user
spring.r2dbc.password=password
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=10

# OAuth2 Resource Server Configuration (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/bank
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/bank/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/bank/protocol/openid-connect/token