apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if and .Values.global .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--import-realm"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_DB
              value: "{{ .Values.keycloak.db }}"
            - name: KC_HOSTNAME_URL
              value: "{{ .Values.keycloak.hostnameUrl }}"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "{{ .Values.keycloak.hostnameAdminUrl }}"
            - name: KC_HOSTNAME_STRICT
              value: "{{ .Values.keycloak.hostnameStrict }}"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "{{ .Values.keycloak.hostnameStrictHttps }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: realm-config
          configMap:
            name: {{ .Chart.Name }}-realm-config
