apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  application.yaml: |
    spring:
      application:
        name: {{ .Chart.Name }}
      cloud:
        consul:
          host: {{ .Values.global.consul.host | default "consul" }}
          port: {{ .Values.global.consul.port | default 8500 }}
          discovery:
            enabled: true
            preferIpAddress: true
            serviceName: {{ .Chart.Name }}
        loadbalancer:
          enabled: true
    gateway:
      service:
        name: gateway
