# Настройки Consul
replicaCount: 1

image:
  repository: "hashicorp/consul"
  tag: "1.17"
  pullPolicy: "IfNotPresent"

service:
  type: "ClusterIP"
  httpPort: 8500
  dnsPort: 8600

# Настройки Consul
consul:
  dataDir: "/consul/data"
  configDir: "/consul/config"
  bindInterface: "eth0"
  client: "0.0.0.0"

# Ресурсы
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Хранилище
persistence:
  enabled: true
  size: "2Gi"
  storageClass: ""
  accessModes:
    - "ReadWriteOnce"

livenessProbe:
  exec:
    command:
      - "consul"
      - "members"
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - "consul"
      - "members"
  initialDelaySeconds: 10
  periodSeconds: 5
