apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-init-scripts
  labels:
    app: {{ .Chart.Name }}
data:
  1-init.sql: |
    -- Создание схем для каждого сервиса
    {{- range .Values.schemas }}
    CREATE SCHEMA IF NOT EXISTS {{ . }};
    {{- end }}

