apiVersion: network.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: accounts
        - podSelector:
            matchLabels:
              app: cash
        - podSelector:
            matchLabels:
              app: transfer
        - podSelector:
            matchLabels:
              app: notifications
      ports:
        - protocol: TCP
          port: 5432
  egress: []
