apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  DATABASE_USERNAME: "{{ .Values.postgresql.username }}"
  DATABASE_PASSWORD: "{{ .Values.postgresql.password }}"
  JWT_SECRET: "{{ .Values.jwt.secret }}"
  JWT_EXPIRATION: "{{ .Values.jwt.expiration }}"
  OAUTH2_CLIENT_SECRET: "{{ .Values.oauth2.clientSecret }}"
  KEYCLOAK_ISSUER_URI: "{{ .Values.keycloak.issuerUri }}"
  KEYCLOAK_JWK_SET_URI: "{{ .Values.keycloak.jwkSetUri }}"
